services:
  frontend:
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile
    ports:
      - 5173:80  
    container_name: bloglist-frontend-prod

  backend:
    build:
      context: ./bloglist-backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb+srv://eperry2688:mongodbpassword@cluster0.meev38s.mongodb.net/bloglistApp?retryWrites=true&w=majority
      - NODE_ENV=production
    ports:
      - 3003:3003
    container_name: bloglist-backend-prod

  nginx:
    image: nginx:1.20.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./bloglist-frontend/dist:/usr/share/nginx/html  # Point to the build output
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
